### PR TITLE
-

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Undefishin** [comment]
> Made the home button take you back to the VM list instead of doing nothing when clicked
hallelujah

**Comment by TabbyEgg** [comment]
i have made a account to say that home button change SHOULD BE CHANGED ASAP

**Comment by Undefishin** [comment]
Wow. a change so wanted that even some random dude made a brand new account just to claim that they wanted the home button to work. just, wow.

**Comment by Undefishin** [comment]
in all seriousness it took long enough just to get that damn button to function, also the url hash thing is nice, ive been wanting to take advantage of that for a while

**Comment by TabbyEgg** [comment]
i always keep pressing that home button thinking it would work 💀

**Comment by Undefishin** [comment]
trust me man, you're not the only one

**Comment by Undefishin** [comment]
if you see this message, react with :cerealspit:

**Comment by dakrk** [comment]
fat nuts

**Pull request merged**
