### PR TITLE
Ru Translate (Better)

### PR DESCRIPTION
**Pull request by NonameVM**

### CODE REVIEW

**Comment by Glitchy404** [comment]
why did you replace the names?

**Comment by NonameVM** [comment]
The translation is of poor quality, wrong word form, wrong endings, wrong words in some places, wrong pronouns.

**Comment by NonameVM** [comment]
I don't want CollabVM and Undefishin to embarrass themselves in front of the Russians.

**Comment by elijahr2411** [comment]
Can you give me some examples of this please?

**Comment by NonameVM** [comment]
Incorrect : Light theme - "Белая тема"  - Correct : Light There - "Светлая тема"
Incorrect : Please fill out the captcha. - ""Пожалуйста, выложите картчю." ("kartchyu")  -Please fill out the captcha. -""Пожалуйста, пройдите капчу" ("capcha")

**Comment by NonameVM** [comment]
elijah you will have to do the commit again, I did not notice some errors there, I will correct them soon.

**Comment by elijahr2411** [comment]
Sure just open a new PR when you're done

**Pull request merged**
