### PR TITLE
Update index; add favicon and more links

### PR DESCRIPTION
**Pull request by HolyNetworkAdapter**
best i could do for now

### CODE REVIEW

**Comment by elijahr2411** [comment]
that base64 favicon is enough to induce vomiting

**Comment by dfault-user** [comment]
[favicon.txt](https://github.com/computernewb/collab-vm-1.2-webapp/files/10513546/favicon.txt)
offering an alternative on this one

**Comment by dfault-user** [comment]
i offer an alternative: [the already existing favicon](https://computernewb.com/favicon.ico)

**Comment by HolyNetworkAdapter** [comment]
updated, not base64 anymore

**Pull request merged**
